### ISSUE TITLE
[bug] Quits if "Preview Manim Cell" before it finishes

### ISSUE THREAD

**Issue by VladimirFokow** [bhoov/manim-notebook#16]
Is this happening on your side as well?

Example code I'm trying:

```py
from manimlib import *

class Test(Scene):
    def construct(self):
        ##
        circle = Circle()
        self.play(ShowCreation(circle), run_time=3)
```

Steps:

```bash
manimgl

# Press "Preview Manim Cell"

# While it's still executing: "Preview Manim Cell" again -> it quits
```

**Comment by Splines** [comment]
This is wanted behavior as described [here](https://github.com/bhoov/vscode-manim/blob/f0b23914b24b53bfdbaeee5ff746b11e09b9ed85/src/previewCode.ts#L6-L19).

**Comment by VladimirFokow** [comment]
hmm.. After reading that I thought that it would re-run the cell (not quit)

**Comment by Splines** [comment]
For me it works just fine:

https://github.com/user-attachments/assets/1328d465-fd7f-4832-b5ca-4bfb5239f7f5

**Comment by VladimirFokow** [comment]
ok, then maybe arch differences (in on MacOS) - will have to look into that..

**Comment by bhoov** [comment]
I can replicate @VladimirFokow's experience. Pressing the "preview" button before the animation is finished rendering exits the iPython terminal.

I am also on MacOS

**Comment by VladimirFokow** [comment]
looks like on macos, if you press `ctrl+c` while `checkpoint_paste()` is still executing, it quits the ipython

**Comment by bhoov** [comment]
yes, this happens to me as well. I get the following error:

```
.../lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by Splines** [comment]
Just to be sure, could you try with Python 3.12 as well, that's the version I'm using.

**Comment by bhoov** [comment]
I can confirm this still happens with python=3.12

**Comment by Splines** [comment]
Mmh ok, that's unfortunate. So maybe that's something for a new Manim issue with your specific system specs? Feel free to link or use the video [from here](https://github.com/bhoov/vscode-manim/issues/16#issuecomment-2429623106) to show how it's supposed to work.

**Comment by bhoov** [comment]
Just started debugging this tonight, haven't figured out exactly how to fix. 

It seems like the issue of Ctrl-C killing the ipython instance is because of the way the ipython shell is launched. Specifically, if the shell is initialized through manim (see [this line](https://github.com/3b1b/manim/blob/1a65498f977aab7ed505fa7bb660399fa64c19af/manimlib/scene/scene.py#L227)), `ctrl+c` will kill the terminal.

However, normal ipython does not behave this way. Instead, `ctrl+c` sends a "keyboard interrupt" to the running ipython, which corresponds to the nice behavior we see in @Splines' [video](https://github.com/bhoov/vscode-manim/issues/16#issuecomment-2429623106)

What is different about the ipython shell created in these two manners such that it fails on MacOS but not on Windows? I'm baffled 🤷

**Comment by bhoov** [comment]
This is a very important usability issue to fix by v0.1.0 release. As a temporary fix, I propose a configuration variable e.g., `manim-notebook.allowInterruptPreview: false` (by default) that implements @VladimirFokow's original logic to wait until the previous command finishes to run again. If this variable is set to `true`, we can use @Splines' interrupt logic that seems to work on windows

**Comment by Splines** [comment]
However, note that the current logic with the `isExecuting` variable is probably not even working on MacOS, see the docstrings [here](https://github.com/bhoov/manim-notebook/blob/4543f93822ccada625ccb1040e884629fd6599d4/src/previewCode.ts#L9-L22):

>  Note that this is not capturing whether the `checkpoint_paste()` command is still running. Instead, it only captures whether reading/writing to clipboard is currently happening to prevent unpredictable behavior.

This is because while we `await` the sending of the command to the clipboard, we don't actually see when the output of Manim has finished and it's not that easy to do even with the shell integration since Manim is running inside IPython. That means for example that there is no exit code associated to the end of a preview since IPython is still running at that point.

---

For this (and other use cases) to work, I have the idea of implementing a `ManimShell` class inside `manimShell.ts` as additional abstraction layer that provides methods like `executeCommand()`. It could then handle everything related to the states of the terminals like opening a new terminal if one is not already open, capturing the Manim output, executing callback functions when Manim throws an error, signaling that Manim has finished with preview etc.

The basis would be to read the output of the terminal, which I was able to do when a new command is sent recently and `read()` is called immediately after that [as seen here](https://github.com/bhoov/manim-notebook/blob/a793c69b0e573b1a732169b98a19dab3ede8e6f7/src/previewCode.ts#L71-L124) and described [here on SO](https://stackoverflow.com/a/77456264/9655481). For terminals that already run a command I haven't yet been able to achieve this (yet). And even for the use case where I was able to capture the output, it only works for one command, so I'll have to experiment more with the API.

**Comment by bhoov** [comment]
I can confirm that, at least on MacOS, this is not a problem with the integrated terminal on VSCode -- the same behavior of Ctrl+C exiting the entire animation happens when starting the `manimgl...` command from iTerm2.

It looks like the problem is in the IPython's [`InteractiveShellEmbed`](https://github.com/ipython/ipython/blob/6aa7cdc7d5f80edcd083865919e78cd3419e88e7/IPython/terminal/embed.py#L119) and the lack of error handling around `signal.SIGINT`. Not sure why windows has no problem with this. I would guess that since Grant uses MacOS he is also unable to interrupt a currently-rendering animation with a new set of commands. 

This is a tough bug to fix and is likely a problem at a more fundamental level than this extension. How should we move forward?

**Comment by bhoov** [comment]
Could you ask that question on their repo 🙏? Alternatively, I can ask that question late tonight when I am available again

**Comment by Splines** [comment]
> on MacOS always use the terminal.sendText, and never the terminal.shellIntegration.executeCommand

I don't see how this would help. We could still use the shell integration on MacOS, right?

We "just" have to prevent that multiple commands overlap in time. This detection mechanism to lock until the whole command is executed (e.g. preview completely finished and not just command _issued_), can be more or less easily implemented after #30. That is, we disable this nice feature for MacOS while searching for a fix that gets down to the root of the trouble.

**Comment by bhoov** [comment]
I'm not near my computer, so I cannot validate my thought, but I *think* what @VladimirFokow meant was that the sendText command strictly sends the specified text to the terminal -- it does not "auto inject" a Ctrl+C like the executeCommand function does. Which means we MacOS users wouldn't have the strange erroring out behavior.

This said, if your PR works as claimed, this would be a huge step towards merging in the preferred functionality in the future (once we can narrow down the source of the bug). I'm in favor of the command detection feature

**Comment by Splines** [comment]
In #32 (in draft at the time of writing this), for MacOS we don't allow a new command to be executed when one is already executing. So you have to wait until that one is finished.

Should you somehow figure out *any way* to quit just the running IPython command, while not quitting the whole IPython shell itself, let me know. Then we can implement this behavior programmatically. In a future PR, I will send a keyboard interrupt manually anyways (reasons will be explained in this future PR, too cumbersome to explain without context).

**Comment by Splines** [comment]
>  Could you ask that question on their repo 🙏?

Did someone of you @bhoov @VladimirFokow already opened an issue for the MacOS behavior on the [Manim Repo](https://github.com/3b1b/manim/issues)? At least, I couldn't find the issue there.

**Comment by VladimirFokow** [comment]
me no, sorry, didn't have much time yet

**Comment by Splines** [comment]
@VladimirFokow  No worries.

Here is a video you might want to use to explain what you expect to see. While previewing an animation, I've pressed `Ctrl + C`. This sends a keyboard interrupt and then I stay in the IPython shell as expected.

https://github.com/user-attachments/assets/938c134d-160c-4a62-a4f3-40f82fbe70fd

**Comment by VladimirFokow** [comment]
Opened:

https://github.com/3b1b/manim/discussions/2236#discussion-7387511

**Comment by Splines** [comment]
thank you @VladimirFokow 🙌
